- name: Get subnet_id
  include: lookup.yml
  when:
    - subnet_name is defined

- name: Send request to API (create subnet)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  register: subnet
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: subnet.status == 200
  changed_when: false
  when:
    - subnet_name is defined
    - not subnet_id or subnet_id is undefined

- debug:
    msg: "{{ subnet }}"
